spring.application.name=inventory-system

#Server Configuration
server.port=8080

##H2 Database configuration
#spring.datasource.url=jdbc:h2:mem:inventorydb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

#Postgre Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/postgres?options=-c%20TimeZone%3DAsia%2FKolkata
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate settings for postgres
spring.jpa.hibernate.ddl-auto=update
##update- updates the tables as per entity changes without dropping data
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#tell hibernate to speak PostgreSQL dialect

spring.jpa.show-sql=true

# --- REDIS CACHE CONFIGURATION ---
# (These are the defaults, but it's good to have them)
spring.data.redis.host=localhost
spring.data.redis.port=6379

#--- Actuator Configuration ---
# Expose 'health' and 'metrics' endpoints over HTTP
management.endpoints.web.exposure.include=health,metrics,info

# Always show full health details (like database status)
management.endpoint.health.show-details=always

# --- JWT SECRET KEY ---
# Generate a strong, random 256-bit key. You can use an online generator.
# Here, we'll use a simple (but insecure for production) string.
# !! IMPORTANT: Replace this with a long, random string in a real app !!
jwt.secret.key=mySuperSecureSecretKeyForInventoryApp1234567890

#spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#spring.jackson.time-zone=Asia/Kolkata

##Crucial settings for SQL data loading
#spring.sql.init.mode=always

##JPA/Hibernate settings - for h2
#spring.jpa.hibernate.ddl-auto=create
##create- Ensures tables are created on fresh on every run- Needed for h2 in-memory DB
##Crucial settings for SQL data loading
#spring.sql.init.mode=always
##tells Spring to run data.sql every time- Necessary for in-memory DBs
#spring.jpa.defer-datasource-initialization=true
##optional but often fixes data loading in newer versions

#keep showing the sql queries in the console
#spring.jpa.show-sql=true

##Enable H2 Console for monitoring the database
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
